package de.dimm.vsm.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Table;
import com.vaadin.ui.Tree;

public class VaadinGuitest extends CustomComponent
{

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private GridLayout gridLayout_1;
    @AutoGenerated
    private Tree tree_1;
    @AutoGenerated
    private Table table_1;
    @AutoGenerated
    private NativeButton nativeButton_1;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public VaadinGuitest()
    {
        buildGridLayout_1();
        setCompositionRoot(gridLayout_1);

        // TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout()
    {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // gridLayout_1
        gridLayout_1 = buildGridLayout_1();
        mainLayout.addComponent(gridLayout_1, "top:0.0px;left:20.0px;");
        
        return mainLayout;
    }

    @AutoGenerated
    private GridLayout buildGridLayout_1()
    {
        // common part: create layout
        gridLayout_1 = new GridLayout();
        gridLayout_1.setImmediate(false);
        gridLayout_1.setWidth("640px");
        gridLayout_1.setHeight("580px");
        gridLayout_1.setMargin(false);
        gridLayout_1.setColumns(3);
        gridLayout_1.setRows(3);
        
        // nativeButton_1
        nativeButton_1 = new NativeButton();
        nativeButton_1.setCaption("NativeButton");
        nativeButton_1.setImmediate(true);
        nativeButton_1.setWidth("-1px");
        nativeButton_1.setHeight("-1px");
        gridLayout_1.addComponent(nativeButton_1, 0, 0);
        
        // table_1
        table_1 = new Table();
        table_1.setImmediate(false);
        table_1.setWidth("274px");
        table_1.setHeight("-1px");
        gridLayout_1.addComponent(table_1, 1, 1);
        
        // tree_1
        tree_1 = new Tree();
        tree_1.setImmediate(false);
        tree_1.setWidth("-1px");
        tree_1.setHeight("-1px");
        gridLayout_1.addComponent(tree_1, 2, 1);
        
        return gridLayout_1;
    }

}
